code --install-extension vsciot-vscode.vscode-arduino;`
code --install-extension adpyke.codesnap;`
code --install-extension ronaldosena.arduino-snippets;`
code --install-extension formulahendry.auto-rename-tag;`
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus;`
code --install-extension alefragnani.numbered-bookmarks;`
code --install-extension ms-vscode.cpptools;`
code --install-extension formulahendry.code-runner;`
code --install-extension anseki.vscode-color;`
code --install-extension pranaygp.vscode-css-peek;`
code --install-extension batisteo.vscode-django;`
code --install-extension usernamehw.errorlens;`
code --install-extension mhutchie.git-graph;`
code --install-extension codezombiech.gitignore;`
code --install-extension eamodio.gitlens;`
code --install-extension mishkinf.goto-next-previous-member;`
code --install-extension albymor.increment-selection;`
code --install-extension ecmel.vscode-html-css;`
code --install-extension oderwat.indent-rainbow;`
code --install-extension ms-toolsai.jupyter;`
code --install-extension ms-toolsai.jupyter-keymap;`
code --install-extension ms-toolsai.jupyter-renderers;`
code --install-extension ritwickdey.liveserver;`
code --install-extension yzhang.markdown-all-in-one;`
code --install-extension davidanson.vscode-markdownlint;`
code --install-extension asbjornh.vscode-module-templates;`
code --install-extension sandcastle.vscode-open;`
code --install-extension techer.open-in-browser;`
code --install-extension gsgupta.opencv-snippets;`
code --install-extension christian-kohler.path-intellisense;`
code --install-extension platformio.platformio-ide;`
code --install-extension ms-vscode.powershell;`
code --install-extension esbenp.prettier-vscode;`
code --install-extension alefragnani.project-manager;`
code --install-extension ms-python.vscode-pylance;`
code --install-extension ms-python.python;`
code --install-extension njpwerner.autodocstring;`
code --install-extension ionutvmi.reg;`
code --install-extension ms-vscode-remote.remote-ssh;`
code --install-extension ms-vscode-remote.remote-ssh-edit;`
code --install-extension ms-vscode-remote.remote-wsl;`
code --install-extension humao.rest-client;`
code --install-extension silverlakesoftware.searchdocsets-vscode;`
code --install-extension liximomo.sftp;`
code --install-extension richie5um2.vscode-sort-json;`
code --install-extension sourcery.sourcery;`
code --install-extension wayou.vscode-todo-highlight;`
code --install-extension gruntfuggly.todo-tree;`
code --install-extension rebornix.toggle;`
code --install-extension vscodevim.vim;`
code --install-extension visualstudioexptteam.vscodeintellicode;`
code --install-extension vscode-icons-team.vscode-icons;`
code --install-extension tomoki1207.vscode-input-sequence;`
code --install-extension dunstontc.viml;`
code --install-extension tyriar.windows-terminal;`
code --install-extension bierner.markdown-mermaid;`
code --install-extension hediet.vscode-drawio;`
code --install-extension nopeslide.vscode-drawio-plugin-mermaid
